export type News = {
    uuid: string,
    title: string,
    description: string
    keywords: string,
    snippet: string,
    url: string,
    image_url: string,
    language: string,
    published_at: Date,
    source: string,
    categories: string[],
    relevance_score: number | null
}

export function mapToNewsType(data: any): News {
    return {
        uuid: data.uuid,
        title: data.title,
        description: data.description,
        keywords: data.keywords,
        snippet: data.snippet,
        url: data.url,
        image_url: data.image_url,
        language: data.language,
        published_at: new Date(data.published_at),
        source: data.source,
        categories: data.categories,
        relevance_score: data.relevance_score || null,
    };
}

export const otirikNews: News[] = [
    {
        "uuid": "fd1a4174-e6b6-4f55-ac15-0f77047c1746",
        "title": "Kabosu, Famous Shiba Inu Who Inspired Dogecoin, Floki And Other Dog Cryptos, Dies At 18",
        "description": "Kabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.",
        "keywords": "",
        "snippet": "Loading... Loading...\n\nKabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.\n\nWhat Happened: As per an update f...",
        "url": "https://www.benzinga.com/markets/cryptocurrency/24/05/39002274/kabosu-famous-shiba-inu-dog-who-inspired-creation-of-dogecoin-and-other-dog-cryptos-dies-a",
        "image_url": "https://cdn.benzinga.com/files/images/story/2024/05/24/Portrait-Shiba-Inu-Dog-In-Summer-In-The-.jpeg?width=1200&height=800&fit=crop",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "benzinga.com",
        "categories": [
            "business"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "a1e7a2cc-5caa-4e9b-b9bd-56c8373fc4fa",
        "title": "How Germany Lost the Middle East",
        "description": "Berlin’s unequivocal support for Israel has eroded its soft-power footprint in the region.",
        "keywords": "",
        "snippet": "Last October, Germany’s ambassador to Tunisia, Peter Prügel, sparked controversy while speaking at the opening of a new secondary school in the suburbs of Tu...",
        "url": "https://foreignpolicy.com/2024/05/24/germany-israel-gaza-palestine-war-middle-east-politics-soft-power-speech/",
        "image_url": "https://foreignpolicy.com/wp-content/uploads/2024/05/1-germany-israel-middle-east-GettyImages-1712270081.jpg?w=1000",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "foreignpolicy.com",
        "categories": [
            "general",
            "politics"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "b0f7cb42-1d24-40c4-b8c2-3455c66a4e37",
        "title": "A stranger raced to give a Marine vet his final honor: A high school diploma",
        "description": "Richard Remp, a Marine veteran who served in the Vietnam War, received a high school diploma from a Pennsylvania superintendent days before his death.",
        "keywords": "",
        "snippet": "For months, Richard Remp’s friends scrambled to get him a unique gift. Remp — “Gunny” to his friends — was a 98-year-old Marine veteran whose military...",
        "url": "https://www.washingtonpost.com/dc-md-va/2024/05/24/marine-veteran-high-school-diploma/",
        "image_url": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/RCEFLGYL65CNBHKUEQ7WFNJJ4E.jpg&w=1440",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "washingtonpost.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "c1419dca-0753-42e3-a1cf-51b5b7731cbc",
        "title": "The best Memorial Day weekend deals",
        "description": "Score big savings this Memorial Day on home and kitchen, tech, gaming, travel, fashion, and more",
        "keywords": "Logitech, SAMSONITE, allbirds, Stanley, The Home Depot, Bespoke AI, AirPods Pro, Wayfair, Dell, adorama, Oliver Cabell, Canon, Nikon, Bespoke AI appliances, MATTRESS FIRM, Samsung, Booking.com, TEMU, alienware, Bissell, Hospitality, Recreation, Adidas, Kindle, StubHub, Best Buy, Quartz",
        "snippet": "This Memorial Day, honor the heroes and score big with unbeatable sales! From tech to fashion, home goods to travel, retailers nationwide are offering incredibl...",
        "url": "https://qz.com/memorial-day-weekend-2024-deals-1851497650",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/b35779281088a1333403b5a5abcb9537.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "ec34965c-665d-4b49-a539-16750cbf056d",
        "title": "Sam Altman is a mixed blessing for artificial intelligence.",
        "description": "Why Scarlett Johansson accused OpenAI of stealing her voice.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/what-next-tbd/2024/05/sam-altman-is-a-mixed-blessing-for-artificial-intelligence?via=rss",
        "image_url": "https://compote.slate.com/images/b3825aac-20c2-4047-ad52-a5ec1d88410d.jpeg?crop=1560,1040,x0,y0&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "9f239682-11c1-445a-95d0-938c8a61ba54",
        "title": "How American guns fuel Haiti’s gang crisis",
        "description": "Violent criminals are using U.S. weapons to terrorize Haitian citizens. Can a new international force brea their grip on power?",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/a-word/2024/05/how-american-guns-fuel-haitis-gang-crisis?via=rss",
        "image_url": "https://compote.slate.com/images/09fc1681-929d-49eb-9a90-d8e8030d68d2.jpeg?width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "cb5e761b-e7c8-407e-9572-26f85c1b2684",
        "title": "How to deal with differences in religion: Relationship advice from Dear Prudence.",
        "description": "Jenée Desmond-Harris is joined by editors for the Dear Prudence column, Paola de Varona and Bryan Lowder.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/dear-prudence/2024/05/how-to-deal-with-differences-in-religion-relationship-advice-from-dear-prudence?via=rss",
        "image_url": "https://compote.slate.com/images/65103985-d02e-42c4-a262-9968492d59af.jpeg?crop=1262,842,x0,y2&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "e21527b6-ba90-458e-b260-e7fb54240dfb",
        "title": "Target slashes prices, Wendy's one-ups McDonald's, Red Lobster goes bankrupt: Retail news roundup",
        "description": "Plus, Nestle plans to launch a new food line catered to Ozempic and Wegovy users",
        "keywords": "Red Lobster, Walmart, MCDONALD 'S, Nike, WENDY 'S, Skechers, Oreo, Nestle, Target Corporation, Super Bowl, Bluemercury, Inflation, Business, Finance, Online shopping, Lowe, Chili, Cracker Barrel, Adidas, Maxx, TGIFridays, Macy’s, Interest rate, Quartz",
        "snippet": "In the world of retail, Wendy’s is deploying a $3 breakfast bundle to compete with McDonald’s $5 meal deal. Red Lobster has filed for bankruptcy protection ...",
        "url": "https://qz.com/target-walmart-wendys-mcdonalds-red-lobster-inflation-1851497294",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/9b0eeb0f4d05fa71c08b33ebdbb2a182.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "fea4d46b-fa34-45da-b8f7-48db27f7dc2f",
        "title": "Tesla's Autopilot safety, Biden's EV tariffs, and BMW's labor problem: Autos news roundup",
        "description": "Plus, the United Kingdom opens the door for self-driving cars to hit the streets",
        "keywords": "BMW, BMW's, Biden, Disaster, Accident, Business, Finance, MINI Cooper, JAGUAR LAND ROVER, Stellantis, Automotive industry in China, best-selling Urus line, Tesla Model X, Jaguar Land Rover, Electric vehicle, Senate, Self-driving car, Tesla, Inc., pricey SUVs, Carlos Tavares, Lamborghini, Electric cars, Urus, Elon Musk, Volkswagen, EVs, seat belts, Quartz",
        "snippet": "The United States’ tariffs on Chinese electric vehicles continue to be controversial. The measures, poised to quadruple rates on Chinese EV exports, are expec...",
        "url": "https://qz.com/tesla-elon-musk-stellantis-biden-tariffs-china-evs-bmw-1851497481",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/38286d03d5b8301b788a1906d16138ae.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "97d5d746-37f7-47a9-acc8-ce632ac811ad",
        "title": "Ozempic knockoffs, Pfizer's cost-cutting, and AstraZeneca’s future: Pharma news roundup",
        "description": "Plus, a new genetic test predicts how well Ozempic will work on patients",
        "keywords": "Pfizer, AstraZeneca, PFIZER'S, Ozempic, Business, Finance, Health, Medical, Pharma, GLP-1 receptor agonist, Semaglutide, Insulin, Nestle, Type 1 diabetes, Guardant Health, GLP-1, Anti-obesity medication, Pharmaceutical industry, FDA, Peptide therapeutics, Novo Nordisk, U.S. FOOD AND DRUG ADMINISTRATION, Peptide hormones, Biogen, Research and development in the United States, Quartz",
        "snippet": "The millennial-targeted Hims & Hers this week joined other telehealth platforms in offering customers a cheaper, compounded version of semaglutide, the active i...",
        "url": "https://qz.com/ozempic-pfizer-astrazeneca-1851497607",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/4fb259656e780e6eea4a09ff70c5e489.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "fd1a4174-e6b6-4f55-ac15-0f77047c1746",
        "title": "Kabosu, Famous Shiba Inu Who Inspired Dogecoin, Floki And Other Dog Cryptos, Dies At 18",
        "description": "Kabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.",
        "keywords": "",
        "snippet": "Loading... Loading...\n\nKabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.\n\nWhat Happened: As per an update f...",
        "url": "https://www.benzinga.com/markets/cryptocurrency/24/05/39002274/kabosu-famous-shiba-inu-dog-who-inspired-creation-of-dogecoin-and-other-dog-cryptos-dies-a",
        "image_url": "https://cdn.benzinga.com/files/images/story/2024/05/24/Portrait-Shiba-Inu-Dog-In-Summer-In-The-.jpeg?width=1200&height=800&fit=crop",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "benzinga.com",
        "categories": [
            "business"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "a1e7a2cc-5caa-4e9b-b9bd-56c8373fc4fa",
        "title": "How Germany Lost the Middle East",
        "description": "Berlin’s unequivocal support for Israel has eroded its soft-power footprint in the region.",
        "keywords": "",
        "snippet": "Last October, Germany’s ambassador to Tunisia, Peter Prügel, sparked controversy while speaking at the opening of a new secondary school in the suburbs of Tu...",
        "url": "https://foreignpolicy.com/2024/05/24/germany-israel-gaza-palestine-war-middle-east-politics-soft-power-speech/",
        "image_url": "https://foreignpolicy.com/wp-content/uploads/2024/05/1-germany-israel-middle-east-GettyImages-1712270081.jpg?w=1000",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "foreignpolicy.com",
        "categories": [
            "general",
            "politics"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "b0f7cb42-1d24-40c4-b8c2-3455c66a4e37",
        "title": "A stranger raced to give a Marine vet his final honor: A high school diploma",
        "description": "Richard Remp, a Marine veteran who served in the Vietnam War, received a high school diploma from a Pennsylvania superintendent days before his death.",
        "keywords": "",
        "snippet": "For months, Richard Remp’s friends scrambled to get him a unique gift. Remp — “Gunny” to his friends — was a 98-year-old Marine veteran whose military...",
        "url": "https://www.washingtonpost.com/dc-md-va/2024/05/24/marine-veteran-high-school-diploma/",
        "image_url": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/RCEFLGYL65CNBHKUEQ7WFNJJ4E.jpg&w=1440",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "washingtonpost.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "c1419dca-0753-42e3-a1cf-51b5b7731cbc",
        "title": "The best Memorial Day weekend deals",
        "description": "Score big savings this Memorial Day on home and kitchen, tech, gaming, travel, fashion, and more",
        "keywords": "Logitech, SAMSONITE, allbirds, Stanley, The Home Depot, Bespoke AI, AirPods Pro, Wayfair, Dell, adorama, Oliver Cabell, Canon, Nikon, Bespoke AI appliances, MATTRESS FIRM, Samsung, Booking.com, TEMU, alienware, Bissell, Hospitality, Recreation, Adidas, Kindle, StubHub, Best Buy, Quartz",
        "snippet": "This Memorial Day, honor the heroes and score big with unbeatable sales! From tech to fashion, home goods to travel, retailers nationwide are offering incredibl...",
        "url": "https://qz.com/memorial-day-weekend-2024-deals-1851497650",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/b35779281088a1333403b5a5abcb9537.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "ec34965c-665d-4b49-a539-16750cbf056d",
        "title": "Sam Altman is a mixed blessing for artificial intelligence.",
        "description": "Why Scarlett Johansson accused OpenAI of stealing her voice.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/what-next-tbd/2024/05/sam-altman-is-a-mixed-blessing-for-artificial-intelligence?via=rss",
        "image_url": "https://compote.slate.com/images/b3825aac-20c2-4047-ad52-a5ec1d88410d.jpeg?crop=1560,1040,x0,y0&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "9f239682-11c1-445a-95d0-938c8a61ba54",
        "title": "How American guns fuel Haiti’s gang crisis",
        "description": "Violent criminals are using U.S. weapons to terrorize Haitian citizens. Can a new international force brea their grip on power?",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/a-word/2024/05/how-american-guns-fuel-haitis-gang-crisis?via=rss",
        "image_url": "https://compote.slate.com/images/09fc1681-929d-49eb-9a90-d8e8030d68d2.jpeg?width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "cb5e761b-e7c8-407e-9572-26f85c1b2684",
        "title": "How to deal with differences in religion: Relationship advice from Dear Prudence.",
        "description": "Jenée Desmond-Harris is joined by editors for the Dear Prudence column, Paola de Varona and Bryan Lowder.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/dear-prudence/2024/05/how-to-deal-with-differences-in-religion-relationship-advice-from-dear-prudence?via=rss",
        "image_url": "https://compote.slate.com/images/65103985-d02e-42c4-a262-9968492d59af.jpeg?crop=1262,842,x0,y2&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "e21527b6-ba90-458e-b260-e7fb54240dfb",
        "title": "Target slashes prices, Wendy's one-ups McDonald's, Red Lobster goes bankrupt: Retail news roundup",
        "description": "Plus, Nestle plans to launch a new food line catered to Ozempic and Wegovy users",
        "keywords": "Red Lobster, Walmart, MCDONALD 'S, Nike, WENDY 'S, Skechers, Oreo, Nestle, Target Corporation, Super Bowl, Bluemercury, Inflation, Business, Finance, Online shopping, Lowe, Chili, Cracker Barrel, Adidas, Maxx, TGIFridays, Macy’s, Interest rate, Quartz",
        "snippet": "In the world of retail, Wendy’s is deploying a $3 breakfast bundle to compete with McDonald’s $5 meal deal. Red Lobster has filed for bankruptcy protection ...",
        "url": "https://qz.com/target-walmart-wendys-mcdonalds-red-lobster-inflation-1851497294",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/9b0eeb0f4d05fa71c08b33ebdbb2a182.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "fea4d46b-fa34-45da-b8f7-48db27f7dc2f",
        "title": "Tesla's Autopilot safety, Biden's EV tariffs, and BMW's labor problem: Autos news roundup",
        "description": "Plus, the United Kingdom opens the door for self-driving cars to hit the streets",
        "keywords": "BMW, BMW's, Biden, Disaster, Accident, Business, Finance, MINI Cooper, JAGUAR LAND ROVER, Stellantis, Automotive industry in China, best-selling Urus line, Tesla Model X, Jaguar Land Rover, Electric vehicle, Senate, Self-driving car, Tesla, Inc., pricey SUVs, Carlos Tavares, Lamborghini, Electric cars, Urus, Elon Musk, Volkswagen, EVs, seat belts, Quartz",
        "snippet": "The United States’ tariffs on Chinese electric vehicles continue to be controversial. The measures, poised to quadruple rates on Chinese EV exports, are expec...",
        "url": "https://qz.com/tesla-elon-musk-stellantis-biden-tariffs-china-evs-bmw-1851497481",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/38286d03d5b8301b788a1906d16138ae.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "97d5d746-37f7-47a9-acc8-ce632ac811ad",
        "title": "Ozempic knockoffs, Pfizer's cost-cutting, and AstraZeneca’s future: Pharma news roundup",
        "description": "Plus, a new genetic test predicts how well Ozempic will work on patients",
        "keywords": "Pfizer, AstraZeneca, PFIZER'S, Ozempic, Business, Finance, Health, Medical, Pharma, GLP-1 receptor agonist, Semaglutide, Insulin, Nestle, Type 1 diabetes, Guardant Health, GLP-1, Anti-obesity medication, Pharmaceutical industry, FDA, Peptide therapeutics, Novo Nordisk, U.S. FOOD AND DRUG ADMINISTRATION, Peptide hormones, Biogen, Research and development in the United States, Quartz",
        "snippet": "The millennial-targeted Hims & Hers this week joined other telehealth platforms in offering customers a cheaper, compounded version of semaglutide, the active i...",
        "url": "https://qz.com/ozempic-pfizer-astrazeneca-1851497607",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/4fb259656e780e6eea4a09ff70c5e489.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "fd1a4174-e6b6-4f55-ac15-0f77047c1746",
        "title": "Kabosu, Famous Shiba Inu Who Inspired Dogecoin, Floki And Other Dog Cryptos, Dies At 18",
        "description": "Kabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.",
        "keywords": "",
        "snippet": "Loading... Loading...\n\nKabosu, the beloved Shiba Inu pup who inspired the creation of Dogecoin, passed away at the age of 18.\n\nWhat Happened: As per an update f...",
        "url": "https://www.benzinga.com/markets/cryptocurrency/24/05/39002274/kabosu-famous-shiba-inu-dog-who-inspired-creation-of-dogecoin-and-other-dog-cryptos-dies-a",
        "image_url": "https://cdn.benzinga.com/files/images/story/2024/05/24/Portrait-Shiba-Inu-Dog-In-Summer-In-The-.jpeg?width=1200&height=800&fit=crop",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "benzinga.com",
        "categories": [
            "business"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "a1e7a2cc-5caa-4e9b-b9bd-56c8373fc4fa",
        "title": "How Germany Lost the Middle East",
        "description": "Berlin’s unequivocal support for Israel has eroded its soft-power footprint in the region.",
        "keywords": "",
        "snippet": "Last October, Germany’s ambassador to Tunisia, Peter Prügel, sparked controversy while speaking at the opening of a new secondary school in the suburbs of Tu...",
        "url": "https://foreignpolicy.com/2024/05/24/germany-israel-gaza-palestine-war-middle-east-politics-soft-power-speech/",
        "image_url": "https://foreignpolicy.com/wp-content/uploads/2024/05/1-germany-israel-middle-east-GettyImages-1712270081.jpg?w=1000",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "foreignpolicy.com",
        "categories": [
            "general",
            "politics"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "b0f7cb42-1d24-40c4-b8c2-3455c66a4e37",
        "title": "A stranger raced to give a Marine vet his final honor: A high school diploma",
        "description": "Richard Remp, a Marine veteran who served in the Vietnam War, received a high school diploma from a Pennsylvania superintendent days before his death.",
        "keywords": "",
        "snippet": "For months, Richard Remp’s friends scrambled to get him a unique gift. Remp — “Gunny” to his friends — was a 98-year-old Marine veteran whose military...",
        "url": "https://www.washingtonpost.com/dc-md-va/2024/05/24/marine-veteran-high-school-diploma/",
        "image_url": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/RCEFLGYL65CNBHKUEQ7WFNJJ4E.jpg&w=1440",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "washingtonpost.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "c1419dca-0753-42e3-a1cf-51b5b7731cbc",
        "title": "The best Memorial Day weekend deals",
        "description": "Score big savings this Memorial Day on home and kitchen, tech, gaming, travel, fashion, and more",
        "keywords": "Logitech, SAMSONITE, allbirds, Stanley, The Home Depot, Bespoke AI, AirPods Pro, Wayfair, Dell, adorama, Oliver Cabell, Canon, Nikon, Bespoke AI appliances, MATTRESS FIRM, Samsung, Booking.com, TEMU, alienware, Bissell, Hospitality, Recreation, Adidas, Kindle, StubHub, Best Buy, Quartz",
        "snippet": "This Memorial Day, honor the heroes and score big with unbeatable sales! From tech to fashion, home goods to travel, retailers nationwide are offering incredibl...",
        "url": "https://qz.com/memorial-day-weekend-2024-deals-1851497650",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/b35779281088a1333403b5a5abcb9537.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "ec34965c-665d-4b49-a539-16750cbf056d",
        "title": "Sam Altman is a mixed blessing for artificial intelligence.",
        "description": "Why Scarlett Johansson accused OpenAI of stealing her voice.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/what-next-tbd/2024/05/sam-altman-is-a-mixed-blessing-for-artificial-intelligence?via=rss",
        "image_url": "https://compote.slate.com/images/b3825aac-20c2-4047-ad52-a5ec1d88410d.jpeg?crop=1560,1040,x0,y0&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "9f239682-11c1-445a-95d0-938c8a61ba54",
        "title": "How American guns fuel Haiti’s gang crisis",
        "description": "Violent criminals are using U.S. weapons to terrorize Haitian citizens. Can a new international force brea their grip on power?",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/a-word/2024/05/how-american-guns-fuel-haitis-gang-crisis?via=rss",
        "image_url": "https://compote.slate.com/images/09fc1681-929d-49eb-9a90-d8e8030d68d2.jpeg?width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "cb5e761b-e7c8-407e-9572-26f85c1b2684",
        "title": "How to deal with differences in religion: Relationship advice from Dear Prudence.",
        "description": "Jenée Desmond-Harris is joined by editors for the Dear Prudence column, Paola de Varona and Bryan Lowder.",
        "keywords": "",
        "snippet": "If you can't access your feeds, please contact customer support.\n\nThanks! Check your phone for a link to finish setting up your feed.\n\nPlease enter a 10-digit p...",
        "url": "https://slate.com/podcasts/dear-prudence/2024/05/how-to-deal-with-differences-in-religion-relationship-advice-from-dear-prudence?via=rss",
        "image_url": "https://compote.slate.com/images/65103985-d02e-42c4-a262-9968492d59af.jpeg?crop=1262,842,x0,y2&width=1560",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "slate.com",
        "categories": [
            "general"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "e21527b6-ba90-458e-b260-e7fb54240dfb",
        "title": "Target slashes prices, Wendy's one-ups McDonald's, Red Lobster goes bankrupt: Retail news roundup",
        "description": "Plus, Nestle plans to launch a new food line catered to Ozempic and Wegovy users",
        "keywords": "Red Lobster, Walmart, MCDONALD 'S, Nike, WENDY 'S, Skechers, Oreo, Nestle, Target Corporation, Super Bowl, Bluemercury, Inflation, Business, Finance, Online shopping, Lowe, Chili, Cracker Barrel, Adidas, Maxx, TGIFridays, Macy’s, Interest rate, Quartz",
        "snippet": "In the world of retail, Wendy’s is deploying a $3 breakfast bundle to compete with McDonald’s $5 meal deal. Red Lobster has filed for bankruptcy protection ...",
        "url": "https://qz.com/target-walmart-wendys-mcdonalds-red-lobster-inflation-1851497294",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/9b0eeb0f4d05fa71c08b33ebdbb2a182.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "fea4d46b-fa34-45da-b8f7-48db27f7dc2f",
        "title": "Tesla's Autopilot safety, Biden's EV tariffs, and BMW's labor problem: Autos news roundup",
        "description": "Plus, the United Kingdom opens the door for self-driving cars to hit the streets",
        "keywords": "BMW, BMW's, Biden, Disaster, Accident, Business, Finance, MINI Cooper, JAGUAR LAND ROVER, Stellantis, Automotive industry in China, best-selling Urus line, Tesla Model X, Jaguar Land Rover, Electric vehicle, Senate, Self-driving car, Tesla, Inc., pricey SUVs, Carlos Tavares, Lamborghini, Electric cars, Urus, Elon Musk, Volkswagen, EVs, seat belts, Quartz",
        "snippet": "The United States’ tariffs on Chinese electric vehicles continue to be controversial. The measures, poised to quadruple rates on Chinese EV exports, are expec...",
        "url": "https://qz.com/tesla-elon-musk-stellantis-biden-tariffs-china-evs-bmw-1851497481",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/38286d03d5b8301b788a1906d16138ae.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
    {
        "uuid": "97d5d746-37f7-47a9-acc8-ce632ac811ad",
        "title": "Ozempic knockoffs, Pfizer's cost-cutting, and AstraZeneca’s future: Pharma news roundup",
        "description": "Plus, a new genetic test predicts how well Ozempic will work on patients",
        "keywords": "Pfizer, AstraZeneca, PFIZER'S, Ozempic, Business, Finance, Health, Medical, Pharma, GLP-1 receptor agonist, Semaglutide, Insulin, Nestle, Type 1 diabetes, Guardant Health, GLP-1, Anti-obesity medication, Pharmaceutical industry, FDA, Peptide therapeutics, Novo Nordisk, U.S. FOOD AND DRUG ADMINISTRATION, Peptide hormones, Biogen, Research and development in the United States, Quartz",
        "snippet": "The millennial-targeted Hims & Hers this week joined other telehealth platforms in offering customers a cheaper, compounded version of semaglutide, the active i...",
        "url": "https://qz.com/ozempic-pfizer-astrazeneca-1851497607",
        "image_url": "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/4fb259656e780e6eea4a09ff70c5e489.jpg",
        "language": "en",
        "published_at": new Date("2024-05-24T09:11:07.000000Z"),
        "source": "qz.com",
        "categories": [
            "general",
            "business",
            "tech",
            "entertainment"
        ],
        "relevance_score": null,
    },
]